#! /bin/bash
# Created on 13/8/21
# Script to kill safeeyes when I'm presenting and bring it back up after 20 minutes

sleepDuration=1m
killall safeeyes && notify-send "Killing safe-eyes for $sleepDuration" || notify-send "Error in killing" "Cannot kill safeeyes"
sleep $sleepDuration
jotify-send "starting safeeyes" "restarting safeeyes after sleep" 
safeeyes

#notify-send "Nope, not killing" "It's all for your own good.."
